site_name: My Docs
theme:
  name: material
  palette:
    primary: indigo
  language: zh-TW
  features:
    - tabs
repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: squidfunk/mkdocs-material
plugins:
  - git-revision-date
  - search
extra:
  social:
    - icon: fontawesome/brands/medium
      link: https://medium.com/as-a-med-student
