site_name: 內科筆記
theme:
  name: material
  favicon: images/favicon.ico
  palette:
    primary: indigo
  language: zh-TW
  features:
    - tabs
repo_url: https://github.com/htlin222/imnote
repo_name: htlin222/imnote
plugins:
  - git-revision-date
  - search
extra:
  social:
    - icon: fontawesome/brands/medium
      link: https://medium.com/as-a-med-student
